# Generated by Django 5.2.6 on 2025-10-23 20:42

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_pessoa_bairro_remove_pessoa_endereco_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[blog.validators.validar_cpf], verbose_name='CPF'),
        ),
    ]
