# Generated by Django 5.2.6 on 2025-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo_usuario',
            field=models.CharField(choices=[('comum', 'Comum'), ('gerente', 'Gerente'), ('administrador', 'Administrador')], default='comum', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
